### ISSUE TITLE
Select some initial workflows to start work with

### ISSUE THREAD

**Issue by bwlang** [galaxyproject/iwc#10]
- one should be really tiny  (e.g. john's planemo thing)
 - medium sized workflow (maybe from GTN)
 - do we need both types of test data tiny and scientific

**Comment by bwlang** [comment]
@jmchilton can you link me to the smoke test thing you mentioned?

**Comment by bwlang** [comment]
[tiny test workflow](https://github.com/jmchilton/planemo-workflow-test-template/tree/master/example1)

**Comment by bgruening** [comment]
https://github.com/jmchilton/planemo-workflow-test-template has a few example, 2 from them are from the GTN.

**Comment by mvdbeek** [comment]
Closing this now that we have a few workflows checked in.
