### ISSUE TITLE
iwc-workflows membership

### ISSUE THREAD

**Issue by simleo** [galaxyproject/iwc#104]
After the merge of https://github.com/galaxyproject/iwc/pull/74, we got individual workflow test histories on the [LifeMonitor dashboard](https://app.lifemonitor.eu/dashboard). Unfortunately, however, GitHub has a policy of automatically disabling periodic GitHub Actions workflows after 60 days since the last repository activity (see, for instance, [sars-cov-2-pe-illumina-artic-variant-calling](https://github.com/iwc-workflows/sars-cov-2-pe-illumina-artic-variant-calling/actions/workflows/wftest.yml)).

Can I join the [iwc-workflows](https://github.com/iwc-workflows) organization, with sufficient permissions to enable workflows? This would allow me to manually re-enable workflows as needed and would also pave the way for automation in the near future with the GitHub app we're developing (for that I'm going to also need permissions to install / configure GitHub apps, I guess).

CC: @kikkomep @ilveroluca

**Comment by mvdbeek** [comment]
Alright, you should have an invitation with the necessary permissions now, let me know if that's not the case.

**Comment by simleo** [comment]
Thanks @mvdbeek! I've re-enabled all GitHub workflows

**Comment by simleo** [comment]
Tests for the following workflows have been failing since the reactivation:

![lm_iwc_failing_2022-05-23](https://user-images.githubusercontent.com/1183171/169821439-2bbff332-becd-4c43-8d72-39f85bd79c90.png)

@pvanheus @simonbray: if you want, you can use LifeMonitor to navigate through the failing builds: go to https://app.lifemonitor.eu/ and click on "Failing" to get the above selection; bar charts on the right represent the status (color) and duration (height) of the latest builds. Click on any bar to open the corresponding page on GitHub Actions (the rightmost bar corresponds to the latest build):

![lm_goto_ci_page](https://user-images.githubusercontent.com/1183171/169823765-32375988-118e-42fc-8a8b-a74354abd233.png)

Any feedback is welcome!

**Comment by wm75** [comment]
@pvanheus haven't checked the logs, but very most likely the ivar-based WF is failing because of incompatibility between bioconda's pangolin3 and the latest pnagoLEARN models (requiring different versions of scikit-learn).
In other words "Latest from Web" as the model source is broken for pangolin3 since couple of model releases. You'd have to switch to pangolin4 to make this work again.
