### ISSUE TITLE
Add best practices document and read-the docs link 

### ISSUE THREAD

**Issue by bwlang** [galaxyproject/iwc#11]
based on:
https://galaxy-iuc-standards.readthedocs.io/en/latest/index.html

**Comment by jmchilton** [comment]
I've started a best practice guide and so far it is all stuff I'm also on the cusp of having linting ready for:

https://github.com/galaxyproject/planemo/blob/79b96c69d82d0b1ed18dfeccf2e63887dd8a0b79/docs/best_practices_workflows.rst

**Comment by mvdbeek** [comment]
I've linked to https://planemo.readthedocs.io/en/latest/best_practices_workflows.html in the main readme!
