### ISSUE TITLE
Add version as tag?

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/iwc#247]
I noticed that when people import a workflow it is difficult to find which version of the workflow it was. Do you think it would be a good idea to automatically (or not) add the version as a tag of the workflow?

**Comment by mvdbeek** [comment]
No, I don't think that's very structured information that we should represent with tags. We can make this more visible:
![Screenshot 2023-10-31 at 10 17 54](https://github.com/galaxyproject/iwc/assets/6804901/448b5d38-3b00-4f63-b080-01fd6e167a67)

**Comment by lldelisle** [comment]
Ah it is just because my version of galaxy is too old...
