### ISSUE TITLE
CI for weekly test is failing because of timeout

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/iwc#542]
Hi,
It seems that the weekly CI is failing because of timeout on chunk 30 with the 2 workflows:
workflows/sars-cov-2-variant-calling/sars-cov-2-ont-artic-variant-calling
workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-artic-ivar-analysis
Should we increase the number of chunks?
https://github.com/galaxyproject/iwc/blob/36c26221c6b837e710e854420812c7ce8500bba7/.github/workflows/ci.yaml#L11

**Comment by mvdbeek** [comment]
I would think there's likely something broken with the workflows, it shouldn't take long to run them.

**Comment by mvdbeek** [comment]
Looks like a zenodo download that is timing out. Did you see this in other weeks as well ?
<img width="1831" alt="Screenshot 2024-09-30 at 17 34 59" src="https://github.com/user-attachments/assets/2ce41bb5-69b2-452e-bcad-322ad64b41a0">

**Comment by lldelisle** [comment]
Yes, 2 weeks ago and 3 weeks ago but last week was fine.. Then no need to increase chunk size for the moment.

**Comment by mvdbeek** [comment]
I've rerun it now as well. We should probably add some maximum job runtime for fetch data jobs
