### ISSUE TITLE
How does one define inputs for TreeValGal?

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/iwc#554]
A clear procedure needs to be developed to gather inputs to run each new assembly: 

- Two assembled haplotypes (same contig names); 
- Optional NCBI gene/rna/protein taxon id and downloaded fasta files; 
- Optional haplotype or reference fasta from two or more closely related species for sequence similarity mapping;
- Run repeatmodeler for repeatmasker if both can be made to work;

**Comment by fubar2** [comment]
FWIW: reminder that the existing documentation includes some notes on inputs and that the current WF is on VGP - on it's way to IWC if I can get the tests workfing.
 
## Basic tracks:

 - Documentation [draft](https://docs.google.com/document/d/1YbQZsFC8oDJIGos5yLFbApumpK4yIz02qfwYEypDfI8)
 - Current [WF on VGP](https://vgp.usegalaxy.org/u/fubar/w/treevalgalaugtwohaps-3)
 
## Dimers, coverage, SV:

- Documentation [draft](https://docs.google.com/document/d/1kFCpCGt7Itb3R1mXiNSigd6_mT7-8J0mjYJppliPYtQ/edit#heading=h.i99j8o3qfj7)
- Current [WF on VGP](https://vgp.usegalaxy.org/u/fubar/w/dimer-density-sv-and-coverage-imported-from-url)
