### ISSUE TITLE
Workflows to write to split collection into 2

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/iwc#583]
We could add 3 general workflows:
- split collection in 2 by samplesplan: one column is identifier, other column is group (new collection name)
- split collection in 2 by pattern: one collection contains identifiers which contains this pattern, another collection with identifiers which do not contain this pattern.
- split collection in 2 by comma-separated values: the user input would be 1,1,1,2,2,2 but this one is more error prone to me.

See #582

**Comment by wm75** [comment]
Yes, but what would be even better would be to have Apply Rules populate additional columns from an optional tabular input.
This way you could freely re-arrange collections based on metadata conatined within a dedicated file.

**Comment by lldelisle** [comment]
Yes but Apply Rule is not so easy for most of users. If @pavanvidem or @wm75 are not working on this. I will do it.

**Comment by pavanvidem** [comment]
I am not currently working on this. 

If we have some usecases of such workflows, we should implement it. If it is only for DESeq2 tool, then I think we should invest time in updating the tool.

**Comment by lldelisle** [comment]
I regularly need to split collection based on pattern so I implemented it in #593
