### ISSUE TITLE
Workflow-specific CI runs

### ISSUE THREAD

**Issue by simleo** [galaxyproject/iwc#71]
For clarity, in the discussion that follows, I will use "workflow" for a scientific workflow and "gh-workflow" for a GitHub Actions workflow.

The fact that the same gh-workflow is run to test all workflows is a problem for monitoring. Since all RO-Crates point to https://api.github.com/repos/galaxyproject/iwc/actions/workflows/workflow_test.yml, the [LifeMonitor dashboard](https://app.lifemonitor.eu/dashboard) ends up showing the same health status and test build history for all workflows, which is not particularly informative. For instance, if the test for `parallel-accession-download/main` fails, the build will be marked as a failure for all workflows, even if all the others are doing fine.

For this reason, it would be useful to run a separate gh-workflow for each workflow. One solution would be to have all these separate gh-workflows in this repository. However, they would have to be added manually by the author of each new workflow. Also, as the number of workflows in the repo increases, its GitHub Actions history could become pretty cluttered. Adding them to each individual repository in iwc-workflows, however, should work. Here are some considerations on the individual gh-workflows:

* They can be much simpler than the main one in iwc, since they only have to run the tests (no deployment, etc.).
* How to author them? They can be generated before repo deployment in the main gh-workflow, much like RO-Crate metadata files are generated now.

* When should they be run? Not at each commit: that would be useless, since updates to the individual repositories are only made after tests run successfully in the main gh-workflow. Instead, they should be run periodically (e.g., with a `cron: '0 3 * * *'`) to check for failures due to changes in dependencies, external references, etc.

**Comment by mvdbeek** [comment]
Workflows can by synced across organizations now without much copy-paste, so 

> One solution would be to have all these separate gh-workflows in this repository. However, they would have to be added manually by the author of each new workflow.

that is my preferred route. We can add the little boiler-plate that is required during the deployment step.

**Comment by simleo** [comment]
@mvdbeek do you mean that the deployment step should add the gh-workflow to the main `iwc` repository itself? Can that be done with the same auth token that's being used for the `iwc-workflows` repos?

**Comment by mvdbeek** [comment]
The deployment step in the iwc repo adds the github workflow to the target repository, that should work just fine with the iwc-workflows PAT.
