### ISSUE TITLE
metadata in one file or two?

### ISSUE THREAD

**Issue by bwlang** [galaxyproject/iwc#8]
## I see advantages to having either path here:  Any thoughts from others?
- new header to workflow data file
- or a separate  data file?

### criteria:
 - flexible 
 - easy for scientists to specify, human readable
 - usable by workflow executors 
    - conveys information to workflow runner
    - GUI can use this info for display

### advantages of one file:
 - meta can't get detached from workflow
 - keeps things simple
### advantages of 2 files:
 - no need to modify workflow specifications to accommodate metadata

**Comment by jgoecks** [comment]
I prefer 1 file for the advantages you mentioned above. We can make metadata optional to ensure compatibility with older workflow specs.

**Comment by bgruening** [comment]
:+1: for the one file option.

**Comment by blankenberg** [comment]
I also prefer one file. 

A few things to consider here:
- Is the downloadable/exportable/importable workflow format going to change sometime soon? The current one isn't so great, but there is a version format entry included (i don't remember if it is actually ever checked though). Perhaps worthwhile to coordinate if so.
- Backwards compatibility, e.g. using a new workflow with metadata in an older version of Galaxy. Probably can't just put a new header line, but setting it as an optional base entry in the json dict would probably work.
- Human readability of the current format is not great, and having the metadata added as above would also lack human readability.
- Addressing engine specificity might require significant work to ensure that the 'generic' description can correctly capture the full (and increasing) feature set of Galaxy workflows..

**Comment by abretaud** [comment]
:+1: for a single file too, but I agree that the current format is not really readable...

**Comment by bwlang** [comment]
I think this is now resolved since galaxy workflows have been extended to store relevant metadata.

**Comment by mvdbeek** [comment]
# Test Results (powered by Planemo)

## Test Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 50.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="1 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 50.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="2" title="1 Failed or Errored">
  </div>
</div>

| Test State | Count |
| ---------- | ----- |
| Total      | 2 |
| Passed     | 1 |
| Error      | 0 |
| Failure    | 1 |
| Skipped    | 0 |


<details open><summary>Failed Tests</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; parallel-accession-download.ga_0</summary><div class="padded">

    **Problems**:
    * ```
      Output with path /tmp/tmp4ujryd3b/SRR044777__7089d91e-8c7e-4347-84f2-ab7dbdd823b8 different than expected, difference (using contains):
      ( /home/runner/work/iwc/iwc/workflows/data-fetching/parallel-accession-download/test-data/SRR044777_head.fastq v. /tmp/tmpspwswat5SRR044777_head.fastq )
      Failed to find 'b'@F47USSH02H1LGA/4'' in history data. (lines_diff=0).
      ```

    #### Workflow invocation details

   * Invocation Messages


   * <details><summary>Steps</summary>

     - **Step 1: Run accessions**:

        * step_state: scheduled


     - **Step 2: Split accessions to collection**:

        * step_state: scheduled

        * <details><summary>Jobs</summary>

          - **Job 1:**

            * Job state is ok

            **Command Line:**

             * ```console
               mkdir ./out && python '/tmp/shed_dir/toolshed.g2.bx.psu.edu/repos/bgruening/split_file_to_collection/6cbe2f30c2d7/split_file_to_collection/split_file_to_collection.py' --out ./out --in '/tmp/tmp_ypmqqwo/files/f/7/b/dataset_f7b44497-0244-46f0-845a-7327cc657864.dat' --ftype 'txt' --chunksize 1 --file_names 'split_file' --file_ext 'txt'
               ```
            **Exit Code:**

             * ```console
               0
               ```
            **Job Parameters:**

             *   | Job parameter | Parameter value |
                 | ------------- | --------------- |
                 | \_\_input\_ext | ` "txt" ` |
                 | \_\_workflow\_invocation\_uuid\_\_ | ` "b84e8c83898411ee89f1cd0095e6bd2f" ` |
                 | chromInfo | ` "/tmp/tmp_ypmqqwo/galaxy-dev/tool-data/shared/ucsc/chrom/?.len" ` |
                 | dbkey | ` "?" ` |
                 | split\_parms | ` {"__current_case__": 5, "input": {"values": [{"id": 1, "src": "hda"}]}, "newfilenames": "split_file", "select_allocate": {"__current_case__": 2, "allocate": "byrow"}, "select_ftype": "txt", "select_mode": {"__current_case__": 0, "chunksize": "1", "mode": "chunk"}} ` |



          </details>

     - **Step 3: to parameter**:

        * step_state: scheduled

        * <details><summary>Jobs</summary>

          - **Job 1:**

            * Job state is ok

            **Command Line:**

             * ```console
               cd ../; python _evaluate_expression_.py
               ```
            **Exit Code:**

             * ```console
               0
               ```
            **Job Parameters:**

             *   | Job parameter | Parameter value |
                 | ------------- | --------------- |
                 | \_\_input\_ext | ` "txt" ` |
                 | \_\_workflow\_invocation\_uuid\_\_ | ` "b84e8c83898411ee89f1cd0095e6bd2f" ` |
                 | chromInfo | ` "/tmp/tmp_ypmqqwo/galaxy-dev/tool-data/shared/ucsc/chrom/?.len" ` |
                 | dbkey | ` "?" ` |
                 | param\_type | ` "text" ` |
                 | remove\_newlines | ` true ` |



          </details>

     - **Step 4: fasterq-dump**:

        * step_state: scheduled

        * <details><summary>Jobs</summary>

          - **Job 1:**

            * Job state is ok

            **Command Line:**

             * ```console
               set -o | grep -q pipefail && set -o pipefail;  mkdir -p ~/.ncbi && cp '/tmp/tmp_ypmqqwo/job_working_directory/000/4/configs/tmpv71hwnqb' ~/.ncbi/user-settings.mkfg && vdb-config -s "/repository/user/main/public/root=$PWD" && vdb-config -s "/repository/user/ad/public/root=$PWD" && vdb-config -s "/repository/user/default-path=$PWD" && vdb-config -s "/repository/user/main/public/root=$PWD" && vdb-config -s /http/timeout/read=10000 &&   export SRA_PREFETCH_RETRIES=3 && export SRA_PREFETCH_ATTEMPT=1 &&   echo 'SRR044777' | sed -r 's/(\,|\;|__cn__)/\n/g' > accessions && for acc in $(cat ./accessions); do ( echo "Downloading accession: $acc..." &&  while [ $SRA_PREFETCH_ATTEMPT -le $SRA_PREFETCH_RETRIES ] ; do fasterq-dump "$acc" -e ${GALAXY_SLOTS:-1} --seq-defline '@$sn/$ri' --qual-defline '+' --split-3 --skip-technical 2>&1 | tee -a '/tmp/tmp_ypmqqwo/job_working_directory/000/4/outputs/dataset_9ec9786b-4d77-4206-a65e-ee0c0cf0e5f6.dat'; if [ $? == 0 ] && [ $(ls *.fastq | wc -l) -ge 1 ]; then break ; else echo "Prefetch attempt $SRA_PREFETCH_ATTEMPT of $SRA_PREFETCH_RETRIES exited with code $?" ; SRA_PREFETCH_ATTEMPT=`expr $SRA_PREFETCH_ATTEMPT + 1` ; sleep 1 ; fi ; done && mkdir -p output && mkdir -p outputOther && count="$(ls *.fastq | wc -l)" && echo "There are $count fastq files" && data=($(ls *.fastq)) && if [ "$count" -eq 1 ]; then pigz -cqp ${GALAXY_SLOTS:-1} "${data[0]}" > output/"${acc}"__single.fastqsanger.gz && rm "${data[0]}"; elif [ "--split-3" = "--split-3" ]; then if [ -e "${acc}".fastq ]; then pigz -cqp ${GALAXY_SLOTS:-1} "${acc}".fastq > outputOther/"${acc}"__single.fastqsanger.gz; fi && pigz -cqp ${GALAXY_SLOTS:-1} "${acc}"_1.fastq > output/"${acc}"_forward.fastqsanger.gz && pigz -cqp ${GALAXY_SLOTS:-1} "${acc}"_2.fastq > output/"${acc}"_reverse.fastqsanger.gz && rm "${acc}"*.fastq; elif [ "$count" -eq 2 ]; then pigz -cqp ${GALAXY_SLOTS:-1} "${data[0]}" > output/"${acc}"_forward.fastqsanger.gz && pigz -cqp ${GALAXY_SLOTS:-1} "${data[1]}" > output/"${acc}"_reverse.fastqsanger.gz && rm "${data[0]}" && rm "${data[1]}"; else for file in ${data[*]}; do pigz -cqp ${GALAXY_SLOTS:-1} "$file" > outputOther/"$file"sanger.gz && rm "$file"; done; fi;  ); done; echo "Done with all accessions."
               ```
            **Exit Code:**

             * ```console
               0
               ```
            **Standard Output:**

             * ```console
               Downloading accession: SRR044777...
               spots read      : 7,882
               reads read      : 31,528
               reads written   : 7,882
               technical reads : 23,646
               There are 1 fastq files
               Done with all accessions.

               ```
            **Job Parameters:**

             *   | Job parameter | Parameter value |
                 | ------------- | --------------- |
                 | \_\_input\_ext | ` "input" ` |
                 | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
                 | \_\_workflow\_invocation\_uuid\_\_ | ` "b84e8c83898411ee89f1cd0095e6bd2f" ` |
                 | adv | ` {"minlen": null, "seq_defline": "@$sn/$ri", "skip_technical": true, "split": "--split-3"} ` |
                 | chromInfo | ` "/tmp/tmp_ypmqqwo/galaxy-dev/tool-data/shared/ucsc/chrom/?.len" ` |
                 | dbkey | ` "?" ` |
                 | input | ` {"__current_case__": 0, "accession": "SRR044777", "input_select": "accession_number"} ` |



          </details>

     - **Step 5: flatten paired output**:

        * step_state: scheduled

        * <details><summary>Jobs</summary>

          - **Job 1:**

            * Job state is ok

            **Job Parameters:**

             *   | Job parameter | Parameter value |
                 | ------------- | --------------- |
                 | \_\_workflow\_invocation\_uuid\_\_ | ` "b84e8c83898411ee89f1cd0095e6bd2f" ` |
                 | input | ` {"values": [{"id": 3, "src": "hdca"}]} ` |
                 | rules | ` {"mapping": [{"collapsible_value": {"__class__": "RuntimeValue"}, "columns": [1], "connectable": true, "editing": false, "is_workflow": false, "type": "list_identifiers"}, {"collapsible_value": {"__class__": "RuntimeValue"}, "columns": [2], "connectable": true, "is_workflow": false, "type": "paired_identifier"}], "rules": [{"collapsible_value": {"__class__": "RuntimeValue"}, "connectable": true, "error": null, "is_workflow": false, "type": "add_column_metadata", "value": "identifier0", "warn": null}, {"collapsible_value": {"__class__": "RuntimeValue"}, "connectable": true, "error": null, "is_workflow": false, "type": "add_column_metadata", "value": "identifier1", "warn": null}, {"collapsible_value": {"__class__": "RuntimeValue"}, "connectable": true, "error": null, "is_workflow": false, "type": "add_column_metadata", "value": "identifier2", "warn": null}]} ` |



          </details>

     - **Step 6: flatten single end output**:

        * step_state: scheduled

        * <details><summary>Jobs</summary>

          - **Job 1:**

            * Job state is ok

            **Job Parameters:**

             *   | Job parameter | Parameter value |
                 | ------------- | --------------- |
                 | \_\_workflow\_invocation\_uuid\_\_ | ` "b84e8c83898411ee89f1cd0095e6bd2f" ` |
                 | input | ` {"values": [{"id": 4, "src": "hdca"}]} ` |
                 | rules | ` {"mapping": [{"collapsible_value": {"__class__": "RuntimeValue"}, "columns": [1], "connectable": true, "editing": false, "is_workflow": false, "type": "list_identifiers"}], "rules": [{"collapsible_value": {"__class__": "RuntimeValue"}, "connectable": true, "error": null, "is_workflow": false, "type": "add_column_metadata", "value": "identifier0", "warn": null}, {"collapsible_value": {"__class__": "RuntimeValue"}, "connectable": true, "error": null, "is_workflow": false, "type": "add_column_metadata", "value": "identifier1", "warn": null}]} ` |



          </details>


   * <details><summary>Other invocation details</summary>
      
     - **history_id**

        * 6b7c9560cafcd5fd
      
     - **history_state**

        * ok
      
     - **invocation_id**

        * 6b7c9560cafcd5fd
      
     - **invocation_state**

        * scheduled
         
     - **workflow_id**

        * 2fda17dcb6c8a760
         </details>



  </div></details>


</details>
<details ><summary>Passed Tests</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; parallel-accession-download.ga_1</summary><div class="padded">


    #### Workflow invocation details

   * Invocation Messages


   * <details><summary>Steps</summary>

     - **Step 1: Run accessions**:

        * step_state: scheduled


     - **Step 2: Split accessions to collection**:

        * step_state: scheduled

        * <details><summary>Jobs</summary>

          - **Job 1:**

            * Job state is ok

            **Command Line:**

             * ```console
               mkdir ./out && python '/tmp/shed_dir/toolshed.g2.bx.psu.edu/repos/bgruening/split_file_to_collection/6cbe2f30c2d7/split_file_to_collection/split_file_to_collection.py' --out ./out --in '/tmp/tmp_ypmqqwo/files/e/b/e/dataset_ebe77d45-5e06-433b-99f0-1e6c4ec6f98e.dat' --ftype 'txt' --chunksize 1 --file_names 'split_file' --file_ext 'txt'
               ```
            **Exit Code:**

             * ```console
               0
               ```
            **Job Parameters:**

             *   | Job parameter | Parameter value |
                 | ------------- | --------------- |
                 | \_\_input\_ext | ` "txt" ` |
                 | \_\_workflow\_invocation\_uuid\_\_ | ` "ed0d1ddb898411ee89f1cd0095e6bd2f" ` |
                 | chromInfo | ` "/tmp/tmp_ypmqqwo/galaxy-dev/tool-data/shared/ucsc/chrom/?.len" ` |
                 | dbkey | ` "?" ` |
                 | split\_parms | ` {"__current_case__": 5, "input": {"values": [{"id": 7, "src": "hda"}]}, "newfilenames": "split_file", "select_allocate": {"__current_case__": 2, "allocate": "byrow"}, "select_ftype": "txt", "select_mode": {"__current_case__": 0, "chunksize": "1", "mode": "chunk"}} ` |



          </details>

     - **Step 3: to parameter**:

        * step_state: scheduled

        * <details><summary>Jobs</summary>

          - **Job 1:**

            * Job state is ok

            **Command Line:**

             * ```console
               cd ../; python _evaluate_expression_.py
               ```
            **Exit Code:**

             * ```console
               0
               ```
            **Job Parameters:**

             *   | Job parameter | Parameter value |
                 | ------------- | --------------- |
                 | \_\_input\_ext | ` "txt" ` |
                 | \_\_workflow\_invocation\_uuid\_\_ | ` "ed0d1ddb898411ee89f1cd0095e6bd2f" ` |
                 | chromInfo | ` "/tmp/tmp_ypmqqwo/galaxy-dev/tool-data/shared/ucsc/chrom/?.len" ` |
                 | dbkey | ` "?" ` |
                 | param\_type | ` "text" ` |
                 | remove\_newlines | ` true ` |



          </details>

     - **Step 4: fasterq-dump**:

        * step_state: scheduled

        * <details><summary>Jobs</summary>

          - **Job 1:**

            * Job state is ok

            **Command Line:**

             * ```console
               set -o | grep -q pipefail && set -o pipefail;  mkdir -p ~/.ncbi && cp '/tmp/tmp_ypmqqwo/job_working_directory/000/10/configs/tmpc6of59ef' ~/.ncbi/user-settings.mkfg && vdb-config -s "/repository/user/main/public/root=$PWD" && vdb-config -s "/repository/user/ad/public/root=$PWD" && vdb-config -s "/repository/user/default-path=$PWD" && vdb-config -s "/repository/user/main/public/root=$PWD" && vdb-config -s /http/timeout/read=10000 &&   export SRA_PREFETCH_RETRIES=3 && export SRA_PREFETCH_ATTEMPT=1 &&   echo 'SRR11953971' | sed -r 's/(\,|\;|__cn__)/\n/g' > accessions && for acc in $(cat ./accessions); do ( echo "Downloading accession: $acc..." &&  while [ $SRA_PREFETCH_ATTEMPT -le $SRA_PREFETCH_RETRIES ] ; do fasterq-dump "$acc" -e ${GALAXY_SLOTS:-1} --seq-defline '@$sn/$ri' --qual-defline '+' --split-3 --skip-technical 2>&1 | tee -a '/tmp/tmp_ypmqqwo/job_working_directory/000/10/outputs/dataset_61203a97-16f7-446f-8332-a6ac30d906d4.dat'; if [ $? == 0 ] && [ $(ls *.fastq | wc -l) -ge 1 ]; then break ; else echo "Prefetch attempt $SRA_PREFETCH_ATTEMPT of $SRA_PREFETCH_RETRIES exited with code $?" ; SRA_PREFETCH_ATTEMPT=`expr $SRA_PREFETCH_ATTEMPT + 1` ; sleep 1 ; fi ; done && mkdir -p output && mkdir -p outputOther && count="$(ls *.fastq | wc -l)" && echo "There are $count fastq files" && data=($(ls *.fastq)) && if [ "$count" -eq 1 ]; then pigz -cqp ${GALAXY_SLOTS:-1} "${data[0]}" > output/"${acc}"__single.fastqsanger.gz && rm "${data[0]}"; elif [ "--split-3" = "--split-3" ]; then if [ -e "${acc}".fastq ]; then pigz -cqp ${GALAXY_SLOTS:-1} "${acc}".fastq > outputOther/"${acc}"__single.fastqsanger.gz; fi && pigz -cqp ${GALAXY_SLOTS:-1} "${acc}"_1.fastq > output/"${acc}"_forward.fastqsanger.gz && pigz -cqp ${GALAXY_SLOTS:-1} "${acc}"_2.fastq > output/"${acc}"_reverse.fastqsanger.gz && rm "${acc}"*.fastq; elif [ "$count" -eq 2 ]; then pigz -cqp ${GALAXY_SLOTS:-1} "${data[0]}" > output/"${acc}"_forward.fastqsanger.gz && pigz -cqp ${GALAXY_SLOTS:-1} "${data[1]}" > output/"${acc}"_reverse.fastqsanger.gz && rm "${data[0]}" && rm "${data[1]}"; else for file in ${data[*]}; do pigz -cqp ${GALAXY_SLOTS:-1} "$file" > outputOther/"$file"sanger.gz && rm "$file"; done; fi;  ); done; echo "Done with all accessions."
               ```
            **Exit Code:**

             * ```console
               0
               ```
            **Standard Output:**

             * ```console
               Downloading accession: SRR11953971...
               spots read      : 2,057
               reads read      : 4,114
               reads written   : 4,114
               There are 2 fastq files
               Done with all accessions.

               ```
            **Job Parameters:**

             *   | Job parameter | Parameter value |
                 | ------------- | --------------- |
                 | \_\_input\_ext | ` "input" ` |
                 | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
                 | \_\_workflow\_invocation\_uuid\_\_ | ` "ed0d1ddb898411ee89f1cd0095e6bd2f" ` |
                 | adv | ` {"minlen": null, "seq_defline": "@$sn/$ri", "skip_technical": true, "split": "--split-3"} ` |
                 | chromInfo | ` "/tmp/tmp_ypmqqwo/galaxy-dev/tool-data/shared/ucsc/chrom/?.len" ` |
                 | dbkey | ` "?" ` |
                 | input | ` {"__current_case__": 0, "accession": "SRR11953971", "input_select": "accession_number"} ` |



          </details>

     - **Step 5: flatten paired output**:

        * step_state: scheduled

        * <details><summary>Jobs</summary>

          - **Job 1:**

            * Job state is ok

            **Job Parameters:**

             *   | Job parameter | Parameter value |
                 | ------------- | --------------- |
                 | \_\_workflow\_invocation\_uuid\_\_ | ` "ed0d1ddb898411ee89f1cd0095e6bd2f" ` |
                 | input | ` {"values": [{"id": 11, "src": "hdca"}]} ` |
                 | rules | ` {"mapping": [{"collapsible_value": {"__class__": "RuntimeValue"}, "columns": [1], "connectable": true, "editing": false, "is_workflow": false, "type": "list_identifiers"}, {"collapsible_value": {"__class__": "RuntimeValue"}, "columns": [2], "connectable": true, "is_workflow": false, "type": "paired_identifier"}], "rules": [{"collapsible_value": {"__class__": "RuntimeValue"}, "connectable": true, "error": null, "is_workflow": false, "type": "add_column_metadata", "value": "identifier0", "warn": null}, {"collapsible_value": {"__class__": "RuntimeValue"}, "connectable": true, "error": null, "is_workflow": false, "type": "add_column_metadata", "value": "identifier1", "warn": null}, {"collapsible_value": {"__class__": "RuntimeValue"}, "connectable": true, "error": null, "is_workflow": false, "type": "add_column_metadata", "value": "identifier2", "warn": null}]} ` |



          </details>

     - **Step 6: flatten single end output**:

        * step_state: scheduled

        * <details><summary>Jobs</summary>

          - **Job 1:**

            * Job state is ok

            **Job Parameters:**

             *   | Job parameter | Parameter value |
                 | ------------- | --------------- |
                 | \_\_workflow\_invocation\_uuid\_\_ | ` "ed0d1ddb898411ee89f1cd0095e6bd2f" ` |
                 | input | ` {"values": [{"id": 12, "src": "hdca"}]} ` |
                 | rules | ` {"mapping": [{"collapsible_value": {"__class__": "RuntimeValue"}, "columns": [1], "connectable": true, "editing": false, "is_workflow": false, "type": "list_identifiers"}], "rules": [{"collapsible_value": {"__class__": "RuntimeValue"}, "connectable": true, "error": null, "is_workflow": false, "type": "add_column_metadata", "value": "identifier0", "warn": null}, {"collapsible_value": {"__class__": "RuntimeValue"}, "connectable": true, "error": null, "is_workflow": false, "type": "add_column_metadata", "value": "identifier1", "warn": null}]} ` |



          </details>


   * <details><summary>Other invocation details</summary>
      
     - **history_id**

        * 2fda17dcb6c8a760
      
     - **history_state**

        * ok
      
     - **invocation_id**

        * 2fda17dcb6c8a760
      
     - **invocation_state**

        * scheduled
         
     - **workflow_id**

        * 2fda17dcb6c8a760
         </details>



  </div></details>


</details>
