### ISSUE TITLE
Improve WF outputs parsing by workflowhub

### ISSUE THREAD

**Issue by wm75** [galaxyproject/iwc#96]
@simleo Galaxy workflows use *labels* for workflow outputs. These are unique within a workflow and used to address the outputs in e.g. workflow tests.

```
            "workflow_outputs": [
                {
                    "label": "filtered_variants",
                    "output_name": "output",
                    "uuid": "d6db8dad-1774-4ec8-a858-26b17a287252"
                }
```

Currently, however, workflowhub reports Galaxy WF outputs like this:
![Screenshot from 2022-02-18 09-37-18](https://user-images.githubusercontent.com/4742081/154648899-dc3a27ae-4e16-4106-ad80-ab0485f637fa.png)

i.e., it uses `output_name` both as ID and Name, while imo it would be more correct and more informative to use a WF output's `label` as its ID.

**Comment by simleo** [comment]
Thanks for this clarification, Wolfgang. This is something to take into account for Workflow Run RO-Crate. Forwarded to the WorkflowHub team as https://github.com/seek4science/seek/issues/904

**Comment by simleo** [comment]
https://github.com/seek4science/seek/issues/904 now fixed
